"""initial schema

Revision ID: 4754f6d7c355
Revises: 
Create Date: 2026-06-14 16:03:24.333199
"""
from alembic import op
import sqlalchemy as sa

revision = '4754f6d7c355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('sinapi_importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_layout', sa.String(length=60), nullable=False),
    sa.Column('sharepoint_modified_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('is_retificacao', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sinapi_competencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('publicada_em', sa.DateTime(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['sinapi_importacoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf', 'ano', 'mes', 'ativa', name='uq_competencia_active_marker')
    )
    op.create_index('ix_competencias_uf_ano_mes', 'sinapi_competencias', ['uf', 'ano', 'mes'], unique=False)
    op.create_table('sinapi_composicoes_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('composicao_codigo', sa.String(length=40), nullable=False),
    sa.Column('item_codigo', sa.String(length=40), nullable=False),
    sa.Column('item_descricao', sa.Text(), nullable=False),
    sa.Column('item_tipo', sa.String(length=20), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('coeficiente', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('valor_sem_encargos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_onerado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_nao_onerado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_id'], ['sinapi_competencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_composicoes_itens_lookup', 'sinapi_composicoes_itens', ['competencia_id', 'composicao_codigo'], unique=False)
    op.create_table('sinapi_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('classe', sa.String(length=120), nullable=True),
    sa.Column('valor_sem_encargos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_onerado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_nao_onerado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('percentual_mao_obra_sem_desoneracao', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('percentual_mao_obra_com_desoneracao', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competencia_id'], ['sinapi_competencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itens_lookup', 'sinapi_itens', ['uf', 'ano', 'mes', 'codigo'], unique=False)
    op.create_index('ix_itens_text', 'sinapi_itens', ['descricao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itens_text', table_name='sinapi_itens')
    op.drop_index('ix_itens_lookup', table_name='sinapi_itens')
    op.drop_table('sinapi_itens')
    op.drop_index('ix_composicoes_itens_lookup', table_name='sinapi_composicoes_itens')
    op.drop_table('sinapi_composicoes_itens')
    op.drop_index('ix_competencias_uf_ano_mes', table_name='sinapi_competencias')
    op.drop_table('sinapi_competencias')
    op.drop_table('sinapi_importacoes')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
